### ISSUE TITLE
Rebuild caches before config import or use `drush deploy`

### ISSUE THREAD

**Issue by andriokha** [hanoii/platformsh-recipes#1]
Hey,

Thanks for putting this all together and documenting it, you're a :star:.

I think there's a slight difference between our deployment process and `drush deploy` (which I tend to assume shows the accumulated wisdom of many deploys in many different situations). In this project we don't rebuild caches prior to the config import if there weren't any DB updates:
https://github.com/hanoii/platformsh-recipes/blob/7a9626c5b48bf3ac9a051c20ed274cdeff444938/.ddev/pimp-my-shell/hooks/post-import-db.d/10-drupal.sh#L12-L15
https://github.com/hanoii/platformsh-recipes/blob/7a9626c5b48bf3ac9a051c20ed274cdeff444938/platformsh-recipes/assets/platformsh/functions/conditional-run.sh#L211-L241

Note how a `drush deploy` does the following:
```sh
drush updatedb --no-cache-clear
drush cache:rebuild
drush config:import
drush cache:rebuild
drush deploy:hook
```

I was thinking it might make sense to harmonize? I was also wondering if it's possible to actually use `drush deploy` without degrading anything? The advantages I see are:
1. We automatically get any changes to the command, eg. things like ensuring a cache rebuild is done before the config import.
2. It's easier to ensure parity between dev and production.
3. It's easier to reason about. (If we had problems deploying a site using this to production and you were away, there'd be an amount of time spent just understanding what's going on, and I think the more we can reduce that the better in general.)

(But I only `scanned conditional-run.sh` and I'm not really sure what's going on with the conditional bits and whether it does more than a vanilla `drush deploy`.)

Thanks!

**Comment by hanoii** [comment]
@andriokha the conditional-run.sh attemtps to only does each of those things conditionally based on hashes of changed files.

i.e., only rebuild caches if most things changes, but not config for example:

https://github.com/hanoii/platformsh-recipes/blob/7a9626c5b48bf3ac9a051c20ed274cdeff444938/platformsh-recipes/assets/platformsh/functions/conditional-run.sh#L193-L242

same thing for other stuff. The idea was to not clear cache unnecessary on config changes (and any other random push or something else, like readmes, scripts, etc.)

Same goes for updb, so by doing it atomically and verbosely I have more control of things. 

The double cache rebuild is something I recently added to another project but it was a multisite so I was using a custom deploy, still using the conditional bits but not using the presets. I will update that and the same for the local alternative.

And I kind of like the clear set of commands that some other obscure (albeit definitely full of wisdom) alias command from drush. I prefer to keep up to it manually but the main reason is the conditional bit.

Thanks for chipping and and feel free to suggest/contribute to this!

**Comment by hanoii** [comment]
> The double cache rebuild is something I recently added to another project but it was a multisite so I was using a custom deploy, still using the conditional bits but not using the presets. I will update that and the same for the local alternative.

Or send a PR :)

But I can definitely do it if you want me to.

**Comment by hanoii** [comment]
And while I fully acknowledge this to be a clear example of confirmation bias, I kind of felt happy that I was never affected by https://github.com/drush-ops/drush/issues/5952 :D

**Comment by hanoii** [comment]
BTW, we might as well add --no-cache-clear to both local and remote updb

**Comment by andriokha** [comment]
Thanks!

> > The double cache rebuild is something I recently added to another project but it was a multisite so I was using a custom deploy, still using the conditional bits but not using the presets. I will update that and the same for the local alternative.
> 
> Or send a PR :)

Yeah I considered it, but wanted to feel it out first, especially the idea of changing to `drush deploy`. But tbh I'm not sure if you're suggesting adding a conditional earlier cache rebuild or one that always run (and if the former, I don't know what logic's appropriate to decide whether one's needed).

> And while I fully acknowledge this to be a clear example of confirmation bias, I kind of felt happy that I was never affected by [drush-ops/drush#5952](https://github.com/drush-ops/drush/issues/5952) :D

I can understand that (: and yet I also think it exemplifies what we lose at the same time. The ratio of people using `drush deploy` to this will always be massive, and you have to maintain and adapt this as it goes to different places and encounters different edge cases. I don't think it's a massive thing, but I do feel there's value in using a shared tool that's battle tested and gets kept up-to-date without any effort on your part, and that is a known quantity to other devs.

It's an interesting idea though to try and avoid unnecessary bits - clearly rebuilding all caches every deploy can be problematic for large sites, and it's not exactly sensible for smaller ones.

**Comment by hanoii** [comment]
Yes, not clearing cache is very important for me and I rather have it as the default, even small sites can benefit from not having unnecessary cache clears. 

Yes I was suggesting adding another conditional one on the preset, but will still be have to be done manually if not using the preset.

I can take care as I am most familiar, thanks!

**Comment by hanoii** [comment]
And all of this is really opt-in, you need to actually opt-in to do it on your platform deploy hook.

**Comment by hanoii** [comment]
I will add it to the ddev/local side of things though.

**Comment by hanoii** [comment]
[platformsh-recipes/.ddev/pimp-my-shell/hooks/post-import-db.d/10-drupal.sh](https://github.com/hanoii/platformsh-recipes/blob/7a9626c5b48bf3ac9a051c20ed274cdeff444938/.ddev/pimp-my-shell/hooks/post-import-db.d/10-drupal.sh#L12-L15)

This is actually https://github.com/hanoii/ddev-drupal/blob/main/pimp-my-shell/hooks/post-import-db.d/10-drupal.sh, will fix there.
